testnet-settings:
  user-workflow:
    workflow-name: "loft-orders-testnet"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.testnet.json"
    secrets-path: ""

mainnet-settings:
  user-workflow:
    workflow-name: "loft-orders"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.mainnet.json"
    secrets-path: ""

local-settings:
  user-workflow:
    workflow-name: "loft-orders-local"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.local.json"
    secrets-path: ""
